# Site settings
title: Sample site at http://rayhightower.github.io/sample
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sample Jekyll site at http://rayhightower.github.cio/sample. Let's see how much information should fit here. This is only a test.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rayhightower.github.io/sample" # the base hostname & protocol for your site
twitter_username: rayhightower
github_username:  rayhightower

# Build settings
markdown: kramdown
